### PR TITLE
FOGL-461 - Fixed get_latest_tasks

### PR DESCRIPTION
**Pull request by amarendra-dianomic**

### CODE REVIEW

**Comment by amarendra-dianomic** [comment]
@vaibhav-ScaleDB this failure will continue to occur intermittently as still we do not have any mechanism to provide a clean (i.e. empty task table) to each test. I have already proposed this, as a pure test requirement, vide [FOGL-410](https://scaledb.atlassian.net/browse/FOGL-410) but I am not sure if it would be provided or if at all it is provided, where exactly its location will be.

**Comment by praveen-garg** [comment]
does not original test data (so called master test data for this module) help here?  if Yes, can we just use that itself?

**Comment by amarendra-dianomic** [comment]
@praveen-garg init data fills scheduled_processes and schedules tables only and the schedules are a kind of long running processes, hence we need a separate test data. Further, tasks table gets filled by scheduler itself and we need a clear tasks table support from scheduler for each test to work reliably.

**Comment by amarendra-dianomic** [comment]
@praveen-garg @vaibhav-ScaleDB please check.

**Comment by vaibhav-ScaleDB** [comment]
Tested, LGTM!! Please resolve conflicts and then we are good to merge.

**Comment by amarendra-dianomic** [comment]
@vaibhav-ScaleDB done. Pl check.

**Pull request merged**
