### PR TITLE
FOGL-3217: Need to escape strings in SQL query

### PR DESCRIPTION
**Pull request by AmandeepArora**
Problem was because of unescaped single quote in string "jeweler's loupe" in readings append SQL query.

### CODE REVIEW

**Comment by AmandeepArora** [comment]
{noformat}
INSERT INTO foglamp.readings ( user_ts, asset_code, read_key, reading ) VALUES ('2019-09-02 07:20:56.112305+00:00','RaspiImageClassify', '99069dee-d1df-40e6-b21f-640bec7d1b59', '{"count":3,"objects":[{"score":10.546875,"label":"cellular telephone, cellular phone, cellphone, cell, mobile phone"},{"score":9.765625,"label":"hard disc, hard disk, fixed disk"},{"score":9.765625,"label":"oscilloscope, scope, cathode-ray oscilloscope, CRO"}]}'), ('2019-09-02 07:20:56.150534+00:00','RaspiImageClassify', '662cb64e-6717-4417-8a90-81647e8d5219', '{"count":3,"objects":[{"score":11.71875,"label":"cellular telephone, cellular phone, cellphone, cell, mobile phone"},{"score":10.546875,"label":"joystick"},{"score":8.59375,"label":"oscilloscope, scope, cathode-ray oscilloscope, CRO"}]}'), ('2019-09-02 07:20:56.231665+00:00','RaspiImageClassify', '4680d79c-02d3-4976-a598-c7783861fe40', '{"count":3,"objects":[{"score":13.28125,"label":"cellular telephone, cellular phone, cellpphone, cell, mobile phone"},{"score":10.9375,"label":"lighter, light, igniter, ignitor"},{"score":8.203125,"label":"joystick"}]}'), ('2019-09-02 07:20:56.268346+00:00','RaspiImageClassify', '25c1dbe6-d96f-4e18-a8f4-ecd9ccd7b06b', '{"count":3,"objects":[{"score":19.140625,"label":"lighter, light, igniter, ignitor"},{"score":15.625,"label":"cellular telephone, cellular phone, cellphone, cell, mobile phone"},{"score":5.859375,"label":"oscilloscope, scope, cathode-ray oscilloscope, CRO"}]}'), ('2019-09-02 07:20:56.367976+00:00','RaspiImageClassify', '2c9c007a-ef55-4626-be9a-81819cb0d458', '{"count":3,"objects":[{"score":19.53125,"label":"lighter, light, igniter, ignitor"},{"score":9.765625,"label":"cellular telephone, cellular phone, cellphone, cell, mobile phone"},{"score":8.984375,"label":"oscilloscope, scope, cathode-ray oscilloscope, CRO"}]}'), ('2019-09-02 07:20:56.401713+00:00','RaspiImageClassify', 'c20ac2da-5122-4980-b46f-4ed1e059a7da', '{"count":3,"objects":[{"score":14.453125,"label":"lighter, light, igniter, ignitor"},{"score":11.71875,"label":"cellular telephone, cellular phone, cellphone, cell, mobile phone"},{"score":11.71875,"label":"oscilloscope, scope, cathode-ray oscilloscope, CRO"}]}'), ('2019-09-02 07:20:56.501096+00:00','RaspiImageClassify', '19a78b90-3851-42cb-bfbe-6fb752e40cb7', '{"count":3,"objects":[{"score":35.15625,"label":"oscilloscope, scope, cathode-ray oscilloscope, CRO"},{"score":8.59375,"label":"loupe, jeweler's loupe"},{"score":7.03125,"label":"cellular telephone, cellular phone, cellphone, cell, mobile phone"}]}'), ('2019-09-02 07:20:56.534667+00:00','RaspiImageClassify', '8e3d29ba-0a8c-4d5c-9da1-5b79396ed48d', '{"count":3,"objects":[{"score":22.265625,"label":"oscilloscope, scope, cathode-ray oscilloscope, CRO"},{"score":16.40625,"label":"cellular telephone, cellular phone, cellphone, cell, mobile phone"},{"score":10.15625,"label":"modem"}]}'), ('2019-09-02 07:20:56.634078+00:00','RaspiImageClassify', 'b7ddc2b3-f124-4873-b195-b6de8ed5ac05', '{"count":3,"objects":[{"score":19.53125,"label":"oscilloscope, scope, cathode-ray oscilloscope, CRO"},{"score":14.453125,"label":"hard disc, hard disk, fixed disk"},{"score":8.59375,"label":"cellular telephone, cellular phone, cellphone, cell, mobile phone"}]}'), ('2019-09-02 07:20:56.668794+00:00','RaspiImageClassify', 'de2af10a-c508-433d-921a-10739df8ec63', '{"count":3,"objects":[{"score":16.015625,"label":"oscilloscope, scope, cathode-ray oscilloscope, CRO"},{"score":14.84375,"label":"hard disc, hard disk, fixed disk"},{"score":8.984375,"label":"cellular telephone, cellular phone, cellphone, cell, mobile phone"}]}'), ('2019-09-02 07:20:56.768467+00:00','RaspiImageClassify', 'b5ca52c1-0483-4396-a6da-c20a8b48b742', '{"count":3,"objects":[{"score":23.828125,"label":"oscilloscope, scope, cathode-ray oscilloscope, CRO"},{"score":13.28125,"label":"loupe, jeweler's loupe"},{"score":6.640625,"label":"cellular telephone, cellular phone, cellphone, cell, mobile phone"}]}'), ('2019-09-02 07:20:56.801318+00:00','RaspiImageClassify', '466e28b4-456e-40dc-8ef5-1b3a7d025172', '{"count":3,"objects":[{"score":12.890625,"label":"loupe, jeweler's loupe"},{"score":11.328125,"label":"cellular telephone, cellular phone, cellphone, cell, mobile phone"},{"score":9.375,"label":"joystick"}]}'), ('2019-09-02 07:20:56.921891+00:00','RaspiImageClassify', '6b2a59da-63a3-438c-8d4a-4d165a5c63e8', '{"count":3,"objects":[{"score":9.765625,"label":"joystick"},{"score":8.984375,"label":"hand blower, blow dryer, blow drier, hair dryer, hair drier"},{"score":8.203125,"label":"projector"}]}'), ('2019-09-02 07:20:56.989153+00:00','RaspiImageClassify', 'ea1c9fee-4721-457e-a675-92006518b414', '{"count":3,"objects":[{"score":25.78125,"label":"projector"},{"score":14.0625,"label":"hand blower, blow dryer, blow drier, hair dryer, hair drier"},{"score":5.46875,"label":"mouse, computer mouse"}]}'), ('2019-09-02 07:20:57.052495+00:00','RaspiImageClassify', '6868090a-f973-4fa9-b62b-f18395c26e74', '{"count":3,"objects":[{"score":22.65625,"label":"hand blower, blow dryer, blow drier, hair dryer, hair drier"},{"score":11.328125,"label":"projector"},{"score":4.6875,"label":"iron, smoothing iron"}]}'), ('2019-09-02 07:20:57.110214+00:00','RaspiImageClassify', 'e1f4cc53-2db1-4978-8078-06c0765d77c0', '{"count":3,"objects":[{"score":21.484375,"label":"lab coat, laboratory coat"},{"score":8.984375,"label":"hand blower, blow dryer, blow drier, hair dryer, hair drier"},{"score":8.203125,"label":"projector"}]}'), ('2019-09-02 07:20:57.221919+00:00','RaspiImageClassify', '38123b4f-9fe4-4bbe-bfb7-eefc978ea7e7', '{"count":3,"objects":[{"score":12.890625,"label":"restaurant, eating house, eating place, eatery"},{"score":9.765625,"label":"desk"},{"score":6.640625,"label":"cannon"}]}'), ('2019-09-02 07:20:57.287508+00:00','RaspiImageClassify', '32d9e670-15a5-40e2-b7e2-8f4cd174cd4d', '{"count":3,"objects":[{"score":21.875,"label":"desk"},{"score":6.640625,"label":"restaurant, eating house, eating place, eatery"},{"score":3.90625,"label":"cannon"}]}'), ('2019-09-02 07:20:57.354564+00:00','RaspiImageClassify', '1e42837f-e432-4dc6-b8b4-df5a857d7ba5', '{"count":3,"objects":[{"score":15.625,"label":"desk"},{"score":6.25,"label":"projector"},{"score":4.296875,"label":"barbershop"}]}'), ('2019-09-02 07:20:57.409388+00:00','RaspiImageClassify', 'f29ef3e3-bb97-4547-b885-7b58daa1a3b9', '{"count":3,"objects":[{"score":7.421875,"label":"restaurant, eating house, eating place, eatery"},{"score":7.421875,"label":"cannon"},{"score":5.859375,"label":"desk"}]}'), ('2019-09-02 07:20:57.522442+00:00','RaspiImageClassify', '3307de9c-76f0-4a34-aeb7-1861472d34c7', '{"count":3,"objects":[{"score":12.890625,"label":"desk"},{"score":8.59375,"label":"restaurant, eating house, eating place, eatery"},{"score":4.6875,"label":"lab coat, laboratory coat"}]}'), ('2019-09-02 07:20:57.586429+00:00','RaspiImageClassify', '258a0515-b488-4b55-bf29-5980ce91c12e', '{"count":3,"objects":[{"score":21.484375,"label":"desk"},{"score":9.765625,"label":"restaurant, eating house, eating place, eatery"},{"score":5.46875,"label":"lab coat, laboratory coat"}]}'), ('2019-09-02 07:20:57.654377+00:00','RaspiImageClassify', '3448c0ac-9e68-45e7-a37c-7e266069e2ba', '{"count":3,"objects":[{"score":14.453125,"label":"desk"},{"score":8.984375,"label":"lab coat, laboratory coat"},{"score":5.859375,"label":"web site, website, internet site, site"}]}'), ('2019-09-02 07:20:57.710632+00:00','RaspiImageClassify', 'f7045b84-80cb-41b3-b986-fb99a8d1cd55', '{"count":3,"objects":[{"score":16.015625,"label":"desk"},{"score":10.546875,"label":"lab coat, laboratory coat"},{"score":5.859375,"label":"hand blower, blow dryer, blow drier, hair dryer, hair drier"}]}'), ('2019-09-02 07:20:57.822087+00:00','RaspiImageClassify', 'e4540cb1-bfd1-4280-89b3-b7546be19684', '{"count":3,"objects":[{"score":16.796875,"label":"desk"},{"score":15.234375,"label":"lab coat, laboratory coat"},{"score":6.25,"label":"cleaver, meat cleaver, chopper"}]}'), ('2019-09-02 07:20:57.889920+00:00','RaspiImageClassify', '822b0e23-08dd-473a-865d-29662bdc36a8', '{"count":3,"objects":[{"score":19.921875,"label":"desk"},{"score":12.109375,"label":"lab coat, laboratory coat"},{"score":5.46875,"label":"hand blower, blow dryer, blow drier, hair dryer, hair drier"}]}'), ('2019-09-02 07:20:57.954251+00:00','RaspiImageClassify', 'baf2a12e-e5b7-46c2-b945-a8f1b7d42094', '{"count":3,"objects":[{"score":13.28125,"label":"desk"},{"score":10.9375,"label":"lab coat, laboratory coat"},{"score":8.984375,"label":"hand blower, blow dryer, blow drier, hair dryer, hair drier"}]}'), ('2019-09-02 07:20:58.009153+00:00','RaspiImageClassify', '5405d698-b6eb-4624-83eb-a33c88bec896', '{"count":3,"objects":[{"score":17.578125,"label":"lab coat, laboratory coat"},{"score":15.625,"label":"desk"},{"score":4.296875,"label":"hand blower, blow dryer, blow drier, hair dryer, hair drier"}]}'), ('2019-09-02 07:20:58.121834+00:00','RaspiImageClassify', '0d30adff-4fa0-45db-8c68-b04fb73fc4e7', '{"count":3,"objects":[{"score":23.4375,"label":"desk"},{"score":12.890625,"label":"lab coat, laboratory coat"},{"score":5.46875,"label":"laptop, laptop computer"}]}'), ('2019-09-02 07:20:58.185153+00:00','RaspiImageClassify', '28a0bd86-f3d0-4569-81e5-c02a948bd706', '{"count":3,"objects":[{"score":27.34375,"label":"desk"},{"score":10.15625,"label":"lab coat, laboratory coat"},{"score":5.46875,"label":"laptop, laptop computer"}]}'), ('2019-09-02 07:20:58.254161+00:00','RaspiImageClassify', '952ec178-6232-46ba-a875-3b5c59a04437', '{"count":3,"objects":[{"score":20.3125,"label":"desk"},{"score":13.671875,"label":"lab coat, laboratory coat"},{"score":7.421875,"label":"hand blower, blow dryer, blow drier, hair dryer, hair drier"}]}'), ('2019-09-02 07:20:58.309583+00:00','RaspiImageClassify', '4b2cf7a3-3aec-40dd-8c32-852693d5c92a', '{"count":3,"objects":[{"score":25.0,"label":"desk"},{"score":12.5,"label":"lab coat, laboratory coat"},{"score":7.03125,"label":"hand blower, blow dryer, blow drier, hair dryer, hair drier"}]}'), ('2019-09-02 07:20:58.421298+00:00','RaspiImageClassify', '6315fda5-bbe9-4d37-99a5-20cc78a92954', '{"count":3,"objects":[{"score":29.6875,"label":"desk"},{"score":12.109375,"label":"lab coat, laboratory coat"},{"score":4.6875,"label":"laptop, laptop computer"}]}'), ('2019-09-02 07:20:58.486326+00:00','RaspiImageClassify', '2e0f06f6-9274-4602-ad51-babaf9e50b98', '{"count":3,"objects":[{"score":28.125,"label":"desk"},{"score":7.8125,"label":"lab coat, laboratory coat"},{"score":5.859375,"label":"laptop, laptop computer"}]}'), ('2019-09-02 07:20:58.554316+00:00','RaspiImageClassify', '756575cf-524c-4ce3-97aa-785e250bef44', '{"count":3,"objects":[{"score":14.84375,"label":"desk"},{"score":10.9375,"label":"lab coat, laboratory coat"},{"score":6.25,"label":"microphone, mike"}]}'), ('2019-09-02 07:20:58.608758+00:00','RaspiImageClassify', 'd8a489d7-cfaa-4e07-8050-1d327632faf0', '{"count":3,"objects":[{"score":17.96875,"label":"desk"},{"score":10.15625,"label":"lab coat, laboratory coat"},{"score":5.078125,"label":"microphone, mike"}]}'), ('2019-09-02 07:20:58.721139+00:00','RaspiImageClassify', 'c2384d82-35c8-4061-bad8-1dcc80ee9368', '{"count":3,"objects":[{"score":14.0625,"label":"desk"},{"score":7.8125,"label":"lab coat, laboratory coat"},{"score":6.25,"label":"photocopier"}]}'), ('2019-09-02 07:20:58.787131+00:00','RaspiImageClassify', '2d62beaa-4dc5-4bae-99e3-e8b2061430b8', '{"count":3,"objects":[{"score":16.796875,"label":"desk"},{"score":7.421875,"label":"lab coat, laboratory coat"},{"score":6.25,"label":"photocopier"}]}'), ('2019-09-02 07:20:58.851530+00:00','RaspiImageClassify', '1156791e-2bac-4c8b-afa2-8548fe2c5514', '{"count":3,"objects":[{"score":18.359375,"label":"desk"},{"score":5.46875,"label":"lab coat, laboratory coat"},{"score":4.6875,"label":"laptop, laptop computer"}]}'), ('2019-09-02 07:20:58.909001+00:00','RaspiImageClassify', '281ebbd7-a6d0-4555-99fe-52f126492725', '{"count":3,"objects":[{"score":18.75,"label":"desk"},{"score":7.03125,"label":"lab coat, laboratory coat"},{"score":5.078125,"label":"microphone, mike"}]}'), ('2019-09-02 07:20:59.022885+00:00','RaspiImageClassify', '00b84359-307c-4a42-a5f7-7c399e2740fe', '{"count":3,"objects":[{"score":16.015625,"label":"desk"},{"score":9.765625,"label":"barbershop"},{"score":9.765625,"label":"lab coat, laboratory coat"}]}'), ('2019-09-02 07:20:59.061483+00:00','RaspiImageClassify', '88e9f876-61f3-4514-b81d-7d7f8639eb5d', '{"count":3,"objects":[{"score":19.140625,"label":"desk"},{"score":12.890625,"label":"lab coat, laboratory coat"},{"score":7.03125,"label":"barbershop"}]}'), ('2019-09-02 07:20:59.100302+00:00','RaspiImageClassify', '0976a788-f736-4bb7-8a25-6f43e17ce300', '{"count":3,"objects":[{"score":16.015625,"label":"desk"},{"score":16.015625,"label":"lab coat, laboratory coat"},{"score":5.46875,"label":"barbershop"}]}'), ('2019-09-02 07:20:59.133534+00:00','RaspiImageClassify', 'ae391926-4634-44c6-b2c5-fbd3691f8071', '{"count":3,"objects":[{"score":19.140625,"label":"lab coat, laboratory coat"},{"score":15.625,"label":"desk"},{"score":4.6875,"label":"hand blower, blow dryer, blow drier, hair dryer, hair drier"}]}'), ('2019-09-02 07:20:59.231211+00:00','RaspiImageClassify', '02ed8920-2322-420e-b358-4757bac01e59', '{"count":3,"objects":[{"score":12.890625,"label":"lab coat, laboratory coat"},{"score":10.546875,"label":"desk"},{"score":7.03125,"label":"laptop, laptop computer"}]}'), ('2019-09-02 07:20:59.266653+00:00','RaspiImageClassify', '9337c0a4-e9db-4500-90a5-02cb8cde35ed', '{"count":3,"objects":[{"score":14.453125,"label":"desk"},{"score":13.28125,"label":"lab coat, laboratory coat"},{"score":7.8125,"label":"laptop, laptop computer"}]}'), ('2019-09-02 07:20:59.362941+00:00','RaspiImageClassify', '12aba04a-02c1-450e-9594-fdb55101cff1', '{"count":3,"objects":[{"score":14.453125,"label":"lab coat, laboratory coat"},{"score":12.890625,"label":"desk"},{"score":4.296875,"label":"photocopier"}]}'), ('2019-09-02 07:20:59.395455+00:00','RaspiImageClassify', 'a0598655-d972-407d-83d3-c5cc7b2b1d26', '{"count":3,"objects":[{"score":21.875,"label":"lab coat, laboratory coat"},{"score":12.109375,"label":"desk"},{"score":5.078125,"label":"cleaver, meat cleaver, chopper"}]}'), ('2019-09-02 07:20:59.428613+00:00','RaspiImageClassify', 'd982f514-4d20-4a9a-8cab-c79ac57522cb', '{"count":3,"objects":[{"score":17.96875,"label":"lab coat, laboratory coat"},{"score":14.84375,"label":"desk"},{"score":4.6875,"label":"microphone, mike"}]}'), ('2019-09-02 07:20:59.462088+00:00','RaspiImageClassify', '36d751ba-671b-4d1e-b251-6e832db733cd', '{"count":3,"objects":[{"score":24.609375,"label":"desk"},{"score":14.84375,"label":"lab coat, laboratory coat"},{"score":3.90625,"label":"microphone, mike"}]}'), ('2019-09-02 07:20:59.495584+00:00','RaspiImageClassify', 'e97a29fe-6f64-4a35-a7d3-2a3ae0d904b5', '{"count":3,"objects":[{"score":21.875,"label":"lab coat, laboratory coat"},{"score":14.453125,"label":"desk"},{"score":3.90625,"label":"photocopier"}]}'), ('2019-09-02 07:20:59.529458+00:00','RaspiImageClassify', '410e1a80-1921-41b7-a070-a0df948dd382', '{"count":3,"objects":[{"score":17.578125,"label":"desk"},{"score":14.453125,"label":"lab coat, laboratory coat"},{"score":3.515625,"label":"hand blower, blow dryer, blow drier, hair dryer, hair drier"}]}'), ('2019-09-02 07:20:59.562205+00:00','RaspiImageClassify', 'd0fff5e9-31b2-4d7f-a613-f262aca2467b', '{"count":3,"objects":[{"score":31.640625,"label":"desk"},{"score":12.890625,"label":"lab coat, laboratory coat"},{"score":3.125,"label":"photocopier"}]}'), ('2019-09-02 07:20:59.595563+00:00','RaspiImageClassify', '0791dee2-7e98-4f6e-813c-fdf64b9f366f', '{"count":3,"objects":[{"score":33.984375,"label":"desk"},{"score":15.625,"label":"lab coat, laboratory coat"},{"score":4.296875,"label":"photocopier"}]}'), ('2019-09-02 07:20:59.628631+00:00','RaspiImageClassify', 'ce45dd5f-813e-4289-90a8-831c74d9e3d5', '{"count":3,"objects":[{"score":22.65625,"label":"desk"},{"score":15.234375,"label":"lab coat, laboratory coat"},{"score":3.515625,"label":"photocopier"}]}'), ('2019-09-02 07:20:59.661972+00:00','RaspiImageClassify', 'ef1169c0-3cdb-489e-a4b2-4bea904a5ce0', '{"count":3,"objects":[{"score":35.546875,"label":"desk"},{"score":8.984375,"label":"lab coat, laboratory coat"},{"score":2.34375,"label":"photocopier"}]}'), ('2019-09-02 07:20:59.697036+00:00','RaspiImageClassify', 'a606eb1e-278a-496f-af60-549983ac8e25', '{"count":3,"objects":[{"score":30.078125,"label":"desk"},{"score":14.84375,"label":"lab coat, laboratory coat"},{"score":3.90625,"label":"photocopier"}]}'), ('2019-09-02 07:20:59.763415+00:00','RaspiImageClassify', 'feceab02-6d4a-4a0d-b630-858cf70852ec', '{"count":3,"objects":[{"score":32.03125,"label":"desk"},{"score":12.109375,"label":"lab coat, laboratory coat"},{"score":3.125,"label":"photocopier"}]}'), ('2019-09-02 07:20:59.865764+00:00','RaspiImageClassify', '7a95ac3f-9a9e-49a6-8738-4e7a6602ecc8', '{"count":3,"objects":[{"score":25.78125,"label":"desk"},{"score":11.71875,"label":"lab coat, laboratory coat"},{"score":3.125,"label":"photocopier"}]}'), ('2019-09-02 07:20:59.900248+00:00','RaspiImageClassify', '6addb335-2c3c-4c50-8bba-4620cb3ebdf7', '{"count":3,"objects":[{"score":25.390625,"label":"desk"},{"score":11.328125,"label":"lab coat, laboratory coat"},{"score":4.6875,"label":"hand blower, blow dryer, blow drier, hair dryer, hair drier"}]}'), ('2019-09-02 07:20:59.999215+00:00','RaspiImageClassify', '8f8be59d-068c-492e-83ec-d824d83fcd50', '{"count":3,"objects":[{"score":33.59375,"label":"desk"},{"score":20.3125,"label":"lab coat, laboratory coat"},{"score":2.734375,"label":"photocopier"}]}'), ('2019-09-02 07:21:00.033690+00:00','RaspiImageClassify', 'd6ceb968-7b41-4405-86bd-2e9c111d52d3', '{"count":3,"objects":[{"score":29.6875,"label":"desk"},{"score":24.21875,"label":"lab coat, laboratory coat"},{"score":3.125,"label":"barbershop"}]}'), ('2019-09-02 07:21:00.132356+00:00','RaspiImageClassify', '78fe091d-1404-4b70-9f2e-293addcc6094', '{"count":3,"objects":[{"score":17.1875,"label":"lab coat, laboratory coat"},{"score":15.625,"label":"desk"},{"score":9.765625,"label":"hand blower, blow dryer, blow drier, hair dryer, hair drier"}]}'), ('2019-09-02 07:21:00.166510+00:00','RaspiImageClassify', 'cf465168-4958-4146-85ba-d9d2464814fd', '{"count":3,"objects":[{"score":17.578125,"label":"hand blower, blow dryer, blow drier, hair dryer, hair drier"},{"score":14.453125,"label":"desk"},{"score":11.71875,"label":"lab coat, laboratory coat"}]}'), ('2019-09-02 07:21:00.262753+00:00','RaspiImageClassify', '5e55cad9-54cd-4bf8-ac33-59b9dc0cc54a', '{"count":3,"objects":[{"score":36.71875,"label":"lab coat, laboratory coat"},{"score":15.234375,"label":"desk"},{"score":5.46875,"label":"barbershop"}]}'), ('2019-09-02 07:21:00.299885+00:00','RaspiImageClassify', '30b7e8e4-fd43-4723-a735-a81760792b1f', '{"count":3,"objects":[{"score":34.375,"label":"lab coat, laboratory coat"},{"score":21.09375,"label":"desk"},{"score":4.6875,"label":"barbershop"}]}'), ('2019-09-02 07:21:00.396120+00:00','RaspiImageClassify', '279d061b-66c2-4f07-8272-c8bc35ff34b9', '{"count":3,"objects":[{"score":23.828125,"label":"lab coat, laboratory coat"},{"score":13.28125,"label":"desk"},{"score":11.71875,"label":"hand blower, blow dryer, blow drier, hair dryer, hair drier"}]}'), ('2019-09-02 07:21:00.433030+00:00','RaspiImageClassify', '4d9492d5-d7ee-4f53-ab76-81edaabde47b', '{"count":3,"objects":[{"score":42.96875,"label":"lab coat, laboratory coat"},{"score":13.28125,"label":"desk"},{"score":4.296875,"label":"barbershop"}]}'), ('2019-09-02 07:21:00.533778+00:00','RaspiImageClassify', '2f406ca4-5abf-4206-9ba2-0e3207b32145', '{"count":3,"objects":[{"score":37.890625,"label":"lab coat, laboratory coat"},{"score":14.0625,"label":"desk"},{"score":3.125,"label":"cleaver, meat cleaver, chopper"}]}'), ('2019-09-02 07:21:00.586281+00:00','RaspiImageClassify', '483329dc-c6ba-48c1-b148-7fa25849c79d', '{"count":3,"objects":[{"score":41.40625,"label":"lab coat, laboratory coat"},{"score":15.234375,"label":"desk"},{"score":3.90625,"label":"barbershop"}]}'), ('2019-09-02 07:21:00.689038+00:00','RaspiImageClassify', '35107645-b3ca-4d8e-8381-c1cddb42cdf7', '{"count":3,"objects":[{"score":33.203125,"label":"lab coat, laboratory coat"},{"score":11.328125,"label":"desk"},{"score":7.421875,"label":"cleaver, meat cleaver, chopper"}]}'), ('2019-09-02 07:21:00.756528+00:00','RaspiImageClassify', 'bccfa883-9969-4fb0-96e5-ec70f3898d75', '{"count":3,"objects":[{"score":28.90625,"label":"lab coat, laboratory coat"},{"score":21.484375,"label":"desk"},{"score":4.6875,"label":"barbershop"}]}'), ('2019-09-02 07:21:00.818514+00:00','RaspiImageClassify', '34441a21-b6e9-40f6-bbcb-10ce1520fadd', '{"count":3,"objects":[{"score":35.15625,"label":"lab coat, laboratory coat"},{"score":17.578125,"label":"desk"},{"score":5.859375,"label":"cleaver, meat cleaver, chopper"}]}'), ('2019-09-02 07:21:00.885520+00:00','RaspiImageClassify', '5ecc6103-33d3-4939-bde4-d73ba4e5309c', '{"count":3,"objects":[{"score":38.28125,"label":"lab coat, laboratory coat"},{"score":15.625,"label":"desk"},{"score":3.515625,"label":"barbershop"}]}'), ('2019-09-02 07:21:00.956411+00:00','RaspiImageClassify', 'f0222d20-bc7a-4c1f-8632-0a95f009628b', '{"count":3,"objects":[{"score":36.328125,"label":"lab coat, laboratory coat"},{"score":26.953125,"label":"desk"},{"score":2.734375,"label":"hand blower, blow dryer, blow drier, hair dryer, hair drier"}]}'), ('2019-09-02 07:21:01.020855+00:00','RaspiImageClassify', 'fcfada0c-2a6a-4720-8a77-f7f2495aa776', '{"count":3,"objects":[{"score":35.546875,"label":"lab coat, laboratory coat"},{"score":16.015625,"label":"desk"},{"score":5.859375,"label":"cleaver, meat cleaver, chopper"}]}'), ('2019-09-02 07:21:01.088355+00:00','RaspiImageClassify', '9f2194fd-b0af-4b8a-af29-3612453a0547', '{"count":3,"objects":[{"score":48.4375,"label":"lab coat, laboratory coat"},{"score":16.40625,"label":"desk"},{"score":2.734375,"label":"photocopier"}]}');
{noformat}

**Comment by AmandeepArora** [comment]
In above SQL query, I was getting error for "jeweler's loupe", the single quote therein has to be replaced to 2 single quotes.

**Comment by pintomax** [comment]
@AmandeepArora do we need any fix in Postgres?
Are the "tests/unit/C/services/storage" tests ok for both?

testRunner.sh, run from sqlite and postgres folder will show any additional issue

**Comment by ashish-jabble** [comment]
FYI, custom JOB CI results can be found [here](http://jenkins.dianomic.com:8080/view/nightly%20jobs/job/foglamp_nightly_build_ub18/221/)

**Comment by AmandeepArora** [comment]
Changes done on postgres side also.

Unit test result:

$ time $FOGLAMP_ROOT/tests/unit/C/scripts/RunAllTests.sh
Compiling libraries...done
Testing ./cmake_sqlite
All tests in ./cmake_sqlite passed
Testing ./plugins/storage/postgres
All tests in ./plugins/storage/postgres passed
Testing ./plugins/storage/common
All tests in ./plugins/storage/common passed
Testing ./plugins/storage/sqlitememory
All tests in ./plugins/storage/sqlitememory passed
Testing ./plugins/common
All tests in ./plugins/common passed
Testing ./common
All tests in ./common passed
Testing ./cmake_pg
All tests in ./cmake_pg passed
Testing ./services/core
All tests in ./services/core passed
Testing ./services/storage/postgres/plugins/common
All tests in ./services/storage/postgres/plugins/common passed
Testing ./services/storage/postgres
All tests in ./services/storage/postgres passed

**Comment by ashish-jabble** [comment]
@AmandeepArora System tests with sqlite engine health is okay (only FogLAMP Pair test one is failing which is NOT related with this change). 
Also I have triggered another Customjob  with **Postgres** engine and results can be found [here](http://jenkins.dianomic.com:8080/view/custom%20jobs/job/foglamp_postgres_ub1804/29/)

**Comment by pintomax** [comment]
@AmandeepArora I meant these tests:

tests/unit/C/services/storage/sqlite/testRunner.sh
tests/unit/C/services/storage/postgres/testRunner.sh
Follow README.rst  in each folder.


I've just checked sqlite in Buster and Ubuntu 16: OK

I suggest a test run in your setup with both engines.

If it's the case a new test can be added.

**Comment by AmandeepArora** [comment]
tests/unit/C/services/storage/sqlite/testRunner.sh
tests/unit/C/services/storage/postgres/testRunner.sh

These worked fine. Only the purge test failed in postgres case.

Failed Tests
============
Test 42 Purge Readings curl -X PUT http://localhost:8080/storage/reading/purge?age=1000&sent=10&flags=purge
    Expected: { "removed" : 2,  "unsentPurged" : 2,  "unsentRetained" : 0,  "readings" : 0 }
    Got: { "removed" : 2,  "unsentPurged" : 0,  "unsentRetained" : 0,  "readings" : 0 }

**Comment by AmandeepArora** [comment]
Tried test on develop branch, no errors. Then switched back to FOGL-3217, no error there also.

```
0 Tests Failed
114 Tests Passed
1 Tests Unchecked
```

**Pull request merged**
