### PR TITLE
FOGL-3615: sqlite busy fixed

### PR DESCRIPTION
**Pull request by sstefano69**
Signed-off-by: Stefano <stefano@dianomic.com>

### CODE REVIEW

**Review by MonikaSharma06 — APPROVED** [review]
lgtm!

**Review by MarkRiddoch — DISMISSED** [review]

**Review by MonikaSharma06 — CHANGES_REQUESTED** [review]
Although it is working fine in Ubuntu18 environment with the same scenario as described in the ticket but on Rpi, I am facing the issue after increasing Reading Rate 1000.

```
Jan 14 11:06:07 raspberrypi FogLAMP Storage[7768]: ERROR: SQLite3 storage plugin raising error: Inserting a row into SQLIte using a prepared command - asset_code :sinusoid: error :database is locked: reading :{"sinusoid":0.866025404,"square":0.5,"max":0.866025404}:
Jan 14 11:06:07 raspberrypi Sine[7815]: ERROR: Append readings: Inserting a row into SQLIte using a prepared command - asset_code :sinusoid: error :database is locked: reading :{"sinusoid":0.866025404,"square":0.5,"max":0.866025404}:
Jan 14 11:06:07 raspberrypi Sine[7815]: ERROR: Still unable to resend buffered data, leaving on resend queue.
Jan 14 11:06:07 raspberrypi FogLAMP Storage[7768]: WARNING: SQLITE_BUSY - record :0: - retry number :2: sleep time ms :10:
Jan 14 11:06:07 raspberrypi FogLAMP Storage[7768]: WARNING: SQLITE_BUSY - record :0: - retry number :4: sleep time ms :10:
Jan 14 11:06:07 raspberrypi FogLAMP Storage[7768]: WARNING: SQLITE_BUSY - record :0: - retry number :3: sleep time ms :10:
Jan 14 11:06:07 raspberrypi FogLAMP Storage[7768]: WARNING: SQLITE_BUSY - record :0: - retry number :5: sleep time ms :10:
Jan 14 11:06:07 raspberrypi FogLAMP Storage[7768]: WARNING: SQLITE_BUSY - record :0: - retry number :4: sleep time ms :10:
Jan 14 11:06:07 raspberrypi FogLAMP Storage[7768]: ERROR: SQLite3 storage plugin raising error: Inserting a row into SQLIte using a prepared command - asset_code :sinusoid: error :database is locked: reading :{"sinusoid":0.743144825}:
Jan 14 11:06:07 raspberrypi sin #1[7831]: ERROR: Append readings: Inserting a row into SQLIte using a prepared command - asset_code :sinusoid: error :database is locked: reading :{"sinusoid":0.743144825}:
Jan 14 11:06:07 raspberrypi sin #1[7831]: ERROR: Still unable to resend buffered data, leaving on resend queue.
Jan 14 11:06:07 raspberrypi FogLAMP Storage[7768]: WARNING: SQLITE_BUSY - record :0: - retry number :1: sleep time ms :10:
Jan 14 11:06:07 raspberrypi FogLAMP Storage[7768]: WARNING: SQLITE_BUSY - record :0: - retry number :5: sleep time ms :10:
Jan 14 11:06:07 raspberrypi FogLAMP Storage[7768]: WARNING: SQLITE_BUSY - record :0: - retry number :2: sleep time ms :10:
Jan 14 11:06:19 raspberrypi FogLAMP Storage[7768]: ERROR: SQLite3 storage plugin raising error: Inserting a row into SQLIte using a prepared command - asset_code :randomwalk1: error :database is locked: reading :{"randomwalk":72,"ema":73.4199903962}:
Jan 14 11:06:19 raspberrypi Random1[7820]: ERROR: Append readings: Inserting a row into SQLIte using a prepared command - asset_code :randomwalk1: error :database is locked: reading :{"randomwalk":72,"ema":73.4199903962}:
Jan 14 11:06:19 raspberrypi Random1[7820]: ERROR: Still unable to resend buffered data, leaving on resend queue.
Jan 14 11:06:19 raspberrypi FogLAMP Storage[7768]: ERROR: SQLite3 storage plugin raising error: Inserting a row into SQLIte using a prepared command - asset_code :sinusoid: error :database is locked: reading :{"sinusoid":0.309016994}:
Jan 14 11:06:19 raspberrypi sin #1[7831]: ERROR: Append readings: Inserting a row into SQLIte using a prepared command - asset_code :sinusoid: error :database is locked: reading :{"sinusoid":0.309016994}:
Jan 14 11:06:19 raspberrypi sin #1[7831]: WARNING: Failed to write readings to storage layer, queue for resend
```

Now if I try to make Reading / sec Rate 100, then:

```
Jan 14 11:27:16 raspberrypi FogLAMP Storage[7768]: ERROR: SQLite3 storage plugin raising error: Inserting a row into SQLIte using a prepared command - asset_code :sinusoid: error :database is locked: reading :{"sinusoid":-0.866025404,"square":-0.5,"max":-0.5}:
Jan 14 11:27:16 raspberrypi Sine[7815]: ERROR: Append readings: Inserting a row into SQLIte using a prepared command - asset_code :sinusoid: error :database is locked: reading :{"sinusoid":-0.866025404,"square":-0.5,"max":-0.5}:
Jan 14 11:27:16 raspberrypi FogLAMP Storage[7768]: WARNING: SQLITE_BUSY - record :0: - retry number :5: sleep time ms :10:
Jan 14 11:27:16 raspberrypi Sine[7815]: ERROR: Still unable to resend buffered data, leaving on resend queue.
Jan 14 11:27:16 raspberrypi FogLAMP Storage[7768]: ERROR: SQLite3 storage plugin raising error: Inserting a row into SQLIte using a prepared command - asset_code :sinusoid: error :database is locked: reading :{"sinusoid":0.0}:
```

**Machine Details:**
RPi4 + buster / 1 GB
Memory card: 32 GB / class 10

**Comment by sstefano69** [comment]
I tested on my RP:
image

base configuration:
* FogLAMP on SQLite
* Sinusoid

image


using this configuration:

image

I loaded data with no problems: 

image

please, provide the performance of your SD using:

```
# Disk
cd ~;\
rm ihs_test_file;\
sync;sync;sync;\
dd  status=progress bs=1M count=1024 if=/dev/zero of=ihs_test_file;\
rm ihs_test_file
```
 
I extended the SQLite  busy timeout, please try this version also.

**Comment by MonikaSharma06** [comment]
Result of the above commands:
Screenshot 2020-01-16 at 2 31 57 PM

Please try to add one more service (say- randomwalk, Benchmark) with default config, after following the steps which you mentioned here. Then you will get the issue.

**Review by MonikaSharma06 — APPROVED** [review]
The  ingest rate + ping performance **was far better** on the same hardware and memory card. i.e. on v1.7.0 and commits of develop branch, early this month.  

Approving as discussed with @MarkRiddoch.  But there is definitely performance degradation given the same hardware reference!

**Pull request merged**
