### PR TITLE
FOGL-41 Template file for Makefile/shell

### PR DESCRIPTION
**Pull request by Terris-Dianomic**

### CODE REVIEW

**Comment by Terris-Dianomic** [comment]
This file should be renamed to __template__.bash

**Comment by Terris-Dianomic** [comment]
Ready for review.

**Comment by praveen-garg** [comment]
```
#!/usr/bin/env bash

# Run with --help for description.
#
# FOGLAMP_BEGIN
# See: http://foglamp.readthedocs.io/
# FOGLAMP_END

__author__="${FULL_NAME}"
__copyright__="Copyright (c) 2017 OSIsoft, LLC"
__license__="Apache 2.0"
__version__="${VERSION}"

USAGE="=== $(basename $0) [OPTION] [args] ===
  
  DESCRIPTION
    This is the script template.

  OPTIONS
    -h, --help        Display this help and exit
        --version     Output version information and exit
        
  EXAMPLES
    $(basename $0) -h
  "

while [[ $1 = -?* ]]; do
  case $1 in

    -h|--help) echo "${USAGE}" ;;

    --version) echo "$(basename $0) ${__version__}" ;;
    
    *) echo "invalid option: '$1'" ;;

  esac
  shift
done

```

let's keep `.sh` only; We have hashbang as  `#!/usr/bin/env bash`
Please make necessary additions, if we want to source only

**Comment by Terris-Dianomic** [comment]
Ready for re-review

**Pull request merged**
