### PR TITLE
removing test data files, used for rest

### PR DESCRIPTION
**Pull request by praveen-garg**

### CODE REVIEW

**Comment by izoratti-dianomic** [comment]
I cannot merge develop again - I mean I can, but it would be complicated.
Can't this be done in the fogbench branch? I will re-merge the fogbench branch then.

**Comment by praveen-garg** [comment]
changed the base branch.

**Comment by praveen-garg** [comment]
I think base should be changed back to develop, now.

**Comment by praveen-garg** [comment]
Merging to develop!

**Pull request merged**
