### PR TITLE
FOGL-1900 : SP/C++ : investigation on the stability

### PR DESCRIPTION
**Pull request by sstefano69**
this a temporary/working in progress code used to guide the solution.

the main problem is that a call like :

	auto res = m_client->request("GET", url);

seems to be (some times) asynchronous (it should not be).

indeed, res.use_count() report 0 once 'request' is executed
and so the following call :

	if (res->status_code.compare("200 OK") == 0)

crashes.

we added some temporary code to check and wait, a sample of an execution, consider the rows having 'DBG 2 ' :

    Sep 26 13:22:49 ubuntu FogLAMP Process[8935]: DBG 1 - use_count -1-
    Sep 26 13:22:49 ubuntu FogLAMP Process[8935]: DBG 2 - use_count -0-
    Sep 26 13:22:49 ubuntu FogLAMP Process[8935]: DBG 6 - use_count -1-
    Sep 26 13:22:49 ubuntu FogLAMP[4846] INFO: scheduler: foglamp.services.core.scheduler.scheduler: Sleeping for 2530.3971378803253 seconds
    Sep 26 13:22:49 ubuntu FogLAMP Process[8935]: DBG 6 - use_count -1-
    Sep 26 13:22:49 ubuntu FogLAMP Process[8935]: SendingProcess loadDataThread: ('readings' stream id 1), readIdx 0, buffer is NOT empty, waiting ...
    Sep 26 13:22:49 ubuntu FogLAMP Process[8935]: DBG 2 - retry - use_count -1-
    Sep 26 13:22:49 ubuntu FogLAMP Process[8935]: DBG 2 - OK - use_count -1-
    Sep 26 13:22:49 ubuntu FogLAMP Process[8935]: DBG 6 - use_count -1-
    
we added another work-around also.

with the current code we were able to handle 2ml of rows with no errors, btw the code is not a final one.

I tried to use :

     * master/Simple-Web-Server-cfe98038ba8d87a042cab6b3ae1eb3e79561cb37
     * Simple-Web-Server-v3.0.0-rc3

but they didn't completely solved the problem.

NOTE : to use the code it is needed before the run :    

    cmd_sql="INSERT INTO  statistics (key, description) VALUES ('READINGS SENT','readings sent north');";\
    sqlite3 -column -cmd ".timeout 5000"  "file:${FOGLAMP_ROOT}/data/foglamp.db"  "${cmd_sql}"

### CODE REVIEW

**Comment by sstefano69** [comment]
@AmandeepArora , 
could you try this new code, 
it is an improvement respect the one I have already provided to you, 
thanks.

**Comment by AmandeepArora** [comment]
@sstefano69 : I tried your code and it seems to be stable. I was able to run your sending process code with around 5500 readings/sec ingress and egress to Pi server and 100 unique assets for around 28 mins without any crashes. More than 9M readings were processed during this time.

**Comment by sstefano69** [comment]
pushed a new version that could radically solve the problem without any workaround: 

using 2 different references to the Simple-Web-Server client, one for reading thread and another for sending operations.

**Comment by AmandeepArora** [comment]
@sstefano69 - Did you push the updated code?

**Pull request closed without merging**
