### PR TITLE
fogbench 0.1

### PR DESCRIPTION
**Pull request by praveen-garg**
template to an asset/sensor reading json object > encode to cbor > send to CoAP *WITHOUT node-red*, decode back to json and print!

### CODE REVIEW

**Comment by izoratti-dianomic** [comment]
fogbench must be moved in benchmarks/fogbench, it is not part of the foglamp main set of modules.

**Comment by praveen-garg** [comment]
Okay, `<parent FogLAMP>/` was confusing. No problem, I shall move this to `/src/python/benchmarks/fogbench`

**Comment by izoratti-dianomic** [comment]
Sorry for the confusion: 

<parent FogLAMP> is by definition the github parent directory, therefore the director **is not /src/python/benchmarks/fogbench**, it is _benchmarks/fogbench_ under the parent FogLAMP project directory.

Let me know if it is not clear.

**Comment by praveen-garg** [comment]
@izoratti-dianomic done, please check.

**Comment by MarkRiddoch** [comment]
@izoratti-dianomic , @vaibhav-ScaleDB  - Whats holding this pull request up? Can we proceed with this or at least define what we need to do to get this merged in?

**Comment by vaibhav-ScaleDB** [comment]
I guess @billehunt and @izoratti have some thoughts in mind to improve this (https://scaledb.atlassian.net/browse/FOGL-437) but the specs are not yet defined. Even if that is the case, we can still go ahead and merge it and take these improvements in version 2 of fogbench

**Comment by izoratti** [comment]
@vaibhav-ScaleDB - I submitted a minor issue (https://github.com/foglamp/FogLAMP/issues/119) to improve the code (already tested, it gets significant improvement. Nothing is holding it on my side. On the contrary, my plan was to merge it anyway next week as part of the 170809.00 branch. So please check the diff with 170809.00 only for the py file and merge.

**Pull request merged**
