### PR TITLE
FOGL-3613 Remove read_key references from FogLAMP

### PR DESCRIPTION
**Pull request by MarkRiddoch**

### CODE REVIEW

**Review by ashish-jabble — CHANGES_REQUESTED** [review]
I still see some of the references for read_key of below files in foglamp directory, which needs to be resolved

https://github.com/foglamp/FogLAMP/blob/2102e47a25a25de66e8c1e2806c9001841f24367/C/tasks/north/sending_process/sending_process.cpp#L193
https://github.com/foglamp/FogLAMP/blob/2102e47a25a25de66e8c1e2806c9001841f24367/C/tasks/north/sending_process/sending_process.cpp#L210
https://github.com/foglamp/FogLAMP/blob/2102e47a25a25de66e8c1e2806c9001841f24367/python/foglamp/common/storage_client/storage_client.py#L427
https://github.com/foglamp/FogLAMP/blob/2102e47a25a25de66e8c1e2806c9001841f24367/python/foglamp/common/storage_client/storage_client.py#L433
https://github.com/foglamp/FogLAMP/blob/2102e47a25a25de66e8c1e2806c9001841f24367/python/foglamp/services/south/ingest.py#L538
https://github.com/foglamp/FogLAMP/blob/2102e47a25a25de66e8c1e2806c9001841f24367/tests/unit/python/foglamp/services/core/api/test_support.py#L179
https://github.com/foglamp/FogLAMP/blob/2102e47a25a25de66e8c1e2806c9001841f24367/tests/unit/python/foglamp/services/core/api/test_support.py#L196
https://github.com/foglamp/FogLAMP/blob/2102e47a25a25de66e8c1e2806c9001841f24367/tests/unit/python/foglamp/services/core/api/test_support.py#L213

**Comment by MarkRiddoch** [comment]
https://github.com/foglamp/FogLAMP/blob/2102e47a25a25de66e8c1e2806c9001841f24367/tests/unit/python/foglamp/services/core/api/test_support.py#L196
> 
> 
> https://github.com/foglamp/FogLAMP/blob/2102e47a25a25de66e8c1e2806c9001841f24367/tests/unit/python/foglamp/services/core/api/test_support.py#L213

The instance in test_support are merely testing the parsing of syslog and are not related to readings so these will stay as arbitrary, random strings.

**Comment by ashish-jabble** [comment]
@MarkRiddoch PR tester check is failing with commit https://github.com/foglamp/FogLAMP/pull/1814/commits/3571d19567a6c470e21d79b43bfabe2a213511c5. And I do not think its worth to fix the tests, could you please delete the test file `tests.unit.python.foglamp.services.south.test_ingest` this is dead code & no longer used.
For more info See FOGL-3258

**Comment by MarkRiddoch** [comment]
> @MarkRiddoch PR tester check is failing with commit [3571d19](https://github.com/foglamp/FogLAMP/commit/3571d19567a6c470e21d79b43bfabe2a213511c5). And I do not think its worth to fix the tests, could you please delete the test file `tests.unit.python.foglamp.services.south.test_ingest` this is dead code & no longer used.
> For more info See FOGL-3258

Bizarrely that unit test passes locally

Screenshot 2020-01-20 at 11 42 16

**Review by ashish-jabble — APPROVED** [review]

**Pull request merged**
