### PR TITLE
Fix for CentOS / RedHat

### PR DESCRIPTION
**Pull request by pintomax**
Fix for CentOS / RedHat

### CODE REVIEW

**Comment by AmandeepArora** [comment]
Please remove "SUDOERS_SRC_RH" for now. And please explore if there is any other alternate approach to make scl enabled at all times. @praveen-garg mentioned that it is possible to do so, but I am not sure if it is desirable and better solution.

**Comment by pintomax** [comment]
@AmandeepArora removed, it was an oversight.
We need to test and merge this. I'll add SQLIte3 changes after that.

I think we can explore an alternative to scl enabled when all the needed work is done.

**Comment by pintomax** [comment]
@Singhal-Vaibhav @AmandeepArora 

I've found this solution, using this branch


[ec2-user@ip-10-0-0-93 FogLAMP]$ sudo -s
[root@ip-10-0-0-93 FogLAMP]# source scl_source enable rh-python36 && make install

**Comment by pintomax** [comment]
This seems OK as well in Makefile:


CMAKE := source scl_source enable rh-python36 && cmake

**Comment by pintomax** [comment]
Added fix:

just type "sudo make install"  where FogLAMP source has been pulled from git

**Pull request merged**
