### PR TITLE
FOGL-3502: fix for start parameter in buckets query

### PR DESCRIPTION
**Pull request by pintomax**
FOGL-3502: fix for start parameter in buckets query

Tested with SQLite storage plugin only

### CODE REVIEW

**Review by MarkRiddoch — CHANGES_REQUESTED** [review]
This looks like a good change, but the unit tests need to be resolved

**Comment by pintomax** [comment]
I see the failures, let's wait @mshariq-nerd GUI test

**Review by shariq1501 — CHANGES_REQUESTED** [review]
When I am hitting this API `http://localhost:8081/foglamp/asset/sinusoid/bucket/1?length=600`
getting error response 
`500: name 'utc_time' is not defined`
I am not sure if there is any change required in api request param from client side?

**Comment by shariq1501** [comment]
@pintomax  Below API endpoints always returning empty `[]` array in response, though there are readings available in DB at that time. 

`http://localhost:8081/foglamp/asset/sinusoid/bucket/1`
`http://localhost:8081/foglamp/asset/sinusoid/bucket/1?length=600`
`http://localhost:8081/foglamp/asset/sinusoid/bucket/10?start=1575555344&length=1198`

**Review by shariq1501 — APPROVED** [review]

**Review by MarkRiddoch — APPROVED** [review]

**Pull request merged**
