### PR TITLE
Fogl 477 - implements statistics handling 

### PR DESCRIPTION
**Pull request by sstefano69**

### CODE REVIEW

**Comment by vaibhav-ScaleDB** [comment]
@sstefano69 It is almost impossible to review pull with around 5k lines of code change, moreover my previous comments in https://github.com/foglamp/FogLAMP/pull/142 are lost. I will have to reverify those review comments by looking at that pull. Secondly, I am not sure which ticket we are targeting in this pull - Sending process and/or Stats handling. If we have a problem in any of the implementation, others things will suffer merging as everything is in single pull.
Please follow these basic guidelines while working with git/github:
1. Every pull request should be as isolated as possible focusing on a single issue/ticket.
2. After you have received review comments on a pull request, address those comments in the same pull instead of opening a new pull request to incorporate review comments. by opening a new pull request, we will not be able to track what has been changed based on the review comments.
3. Keep it small, work incrementally - code/file changes should be minimal in a single pull request focusing on a specific ticket. This will also help to avoid conflicts as there are other people in the team working on different part of the code.

**Comment by sstefano69** [comment]
Hi @vaibhav-ScaleDB ,
I agree with you (sorry for that) and we will follow your suggestions,
we were developing quickly working/modifying the same code.

I commented your feebacks into the #142 and I implemented some on them.

for info, the PR includes :
    - sending process - implementation of the new spec
    - omf translator  - implementation of the new spec
    - statictis       - rewritten completely using the new structure/spec
    - implementation of some feedbacks from the PR #142

at this point, could I proceed with the merge ? or should I wait.

thanks for helping. :-)

**Comment by vaibhav-ScaleDB** [comment]
Please check with Mark.

**Comment by sstefano69** [comment]
close and using manual merge

**Comment by praveen-garg** [comment]
Manual Merge? even if we do  merge via command line, we should not close the PR manually, once merged; github is smart enough to close this PR as merged automatically.

**Pull request closed without merging**
