### PR TITLE
FOGL-3088 separate endpoint added for fetching notification logcode & log entries

### PR DESCRIPTION
**Pull request by ashish-jabble**
**Fixed items**
- [x] /foglamp/notification/logcode endpoint added for getting notification log codes only
- [x] /foglamp/notification/log endpoint added for getting notification log entries
- [x] unit tests
- [x] System tests (Both API & e2e), also fixed some PEP8 error for the file

Local execution results for system tests

**API**
```
PASSED
tests/system/python/TestNotificationServiceAPI test_invalid_create_notification_instance <- api/test_notification.py PASSED
tests/system/python/TestNotificationServiceAPI test_invalid_create_notification_instance <- api/test_notification.py PASSED
tests/system/python/TestNotificationServiceAPI test_invalid_create_notification_instance <- api/test_notification.py PASSED
tests/system/python/TestNotificationServiceAPI test_invalid_create_notification_instance <- api/test_notification.py PASSED
tests/system/python/TestNotificationServiceAPI test_invalid_create_notification_instance <- api/test_notification.py PASSED
tests/system/python/TestNotificationServiceAPI test_invalid_create_notification_instance <- api/test_notification.py PASSED
tests/system/python/TestNotificationServiceAPI test_invalid_create_notification_instance <- api/test_notification.py PASSED
tests/system/python/TestNotificationServiceAPI test_invalid_create_notification_instance <- api/test_notification.py PASSED
tests/system/python/TestNotificationServiceAPI test_invalid_create_notification_instance <- api/test_notification.py PASSED
tests/system/python/TestNotificationServiceAPI test_invalid_create_notification_instance <- api/test_notification.py PASSED
tests/system/python/TestNotificationServiceAPI test_create_valid_notification_instance <- api/test_notification.py PASSED
tests/system/python/TestNotificationServiceAPI test_invalid_update_notification_instance <- api/test_notification.py PASSED
tests/system/python/TestNotificationServiceAPI test_invalid_update_notification_instance <- api/test_notification.py PASSED
tests/system/python/TestNotificationServiceAPI test_invalid_update_notification_instance <- api/test_notification.py PASSED
tests/system/python/TestNotificationServiceAPI test_invalid_update_notification_instance <- api/test_notification.py PASSED
tests/system/python/TestNotificationServiceAPI test_invalid_update_notification_instance <- api/test_notification.py PASSED
tests/system/python/TestNotificationServiceAPI test_invalid_update_notification_instance <- api/test_notification.py PASSED
tests/system/python/TestNotificationServiceAPI test_invalid_name_update_notification_instance <- api/test_notification.py PASSED
tests/system/python/TestNotificationServiceAPI test_update_valid_notification_instance <- api/test_notification.py PASSED
tests/system/python/TestNotificationServiceAPI test_delete_service_without_notification_delete <- api/test_notification.py PASSED
tests/system/python/TestNotificationServiceAPI test_delete_notification_and_service <- api/test_notification.py PASSED
tests/system/python/TestNotificationServiceAPI test_get_notification_logs <- api/test_notification.py PASSED

===== 24 passed, 1 xfailed in 84.72 seconds ===
```
**E2E**

```
PASSED
tests/system/python/TestNotificationService test_get_default_notification_plugins <- e2e/test_e2e_notification_service_with_plugins.py PASSED
tests/system/python/TestNotificationCRUD test_create_notification_instances_with_default_rule_and_channel_python35 <- e2e/test_e2e_notification_service_with_plugins.py Cloning into '/tmp/foglamp-notify-python35'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 231 (delta 16), reused 17 (delta 8), pack-reused 191
Receiving objects: 100% (231/231), 76.88 KiB | 0 bytes/s, done.
Resolving deltas: 100% (99/99), done.
Checking connectivity... done.
PASSED
tests/system/python/TestNotificationCRUD test_create_notification_instances_with_default_rule_and_channel_python35 <- e2e/test_e2e_notification_service_with_plugins.py PASSED
tests/system/python/TestNotificationCRUD test_create_notification_instances_with_default_rule_and_channel_python35 <- e2e/test_e2e_notification_service_with_plugins.py PASSED
tests/system/python/TestNotificationCRUD test_inbuilt_rule_plugin_and_notify_python35_delivery <- e2e/test_e2e_notification_service_with_plugins.py PASSED
tests/system/python/TestNotificationCRUD test_get_notifications_and_log_entry <- e2e/test_e2e_notification_service_with_plugins.py PASSED
tests/system/python/TestNotificationCRUD test_update_notification <- e2e/test_e2e_notification_service_with_plugins.py PASSED
tests/system/python/TestNotificationCRUD test_delete_notification <- e2e/test_e2e_notification_service_with_plugins.py PASSED
tests/system/python/TestSentAndReceiveNotification test_sent_and_receive_notification <- e2e/test_e2e_notification_service_with_plugins.py Cloning into '/tmp/foglamp-south-coap'...
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 301 (delta 0), reused 0 (delta 0), pack-reused 300
Receiving objects: 100% (301/301), 52.42 KiB | 0 bytes/s, done.
Resolving deltas: 100% (103/103), done.
Checking connectivity... done.
Collecting aiocoap==0.3 (from -r /tmp/foglamp-south-coap/python/requirements-coap.txt (line 1))
Collecting cbor2==4.0.0 (from -r /tmp/foglamp-south-coap/python/requirements-coap.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/fd/1a/7e6d84e786d543f271a2922736acb4a28ddc0de76fefe0cff1dc6aa1c3fb/cbor2-4.0.0-py2.py3-none-any.whl
Installing collected packages: aiocoap, cbor2
Successfully installed aiocoap-0.3 cbor2-4.0.0
You are using pip version 8.1.1, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
coap plugin is installed.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1157  100   600  100   557   3495   3245 --:--:-- --:--:-- --:--:--  3508
PASSED
tests/system/python/TestStartStopNotificationService test_shutdown_service_with_schedule_disable <- e2e/test_e2e_notification_service_with_plugins.py PASSED
tests/system/python/TestStartStopNotificationService test_restart_notification_service <- e2e/test_e2e_notification_service_with_plugins.py PASSED

========= 12 passed in 173.12 seconds =======
```

### CODE REVIEW

**Review by MarkRiddoch — COMMENTED** [review]
This doesn't match the resolution requested in the Jira. The Jira was deliberately worded to make the API generic, allowing a set of log code to be fetched, that set being controlled by the caller.

**Comment by ashish-jabble** [comment]
@MarkRiddoch JIRA is asked for separate endpoint as mentioned in first point. So I filtered out from notification/logcode & notification/log

Right now they have excluded "NTF*" log code entries on result of "/foglamp/audit/logcode" API at GUI client side (source dropdown) which actually breaks the pagination because mismatched totalCount value (server Vs client), you may see FOGL-3255.

Also I am not sure for the exclusion of <NTF*> log codes & entries from the endpoint /foglamp/audit result at the API side.
Kindly advise.

**Comment by praveen-garg** [comment]
@MarkRiddoch  I suggest to add a query param: `?filter=NTF*` (prefix can be anything like CON)  or `?exclude=NTF*` and the same LIKE for source `?source=NTF*`

This way we shall be able to keep the existing audit code API to return everything from audit trails. And GUI can filter out NTF* audit stuff with filter or exclude param in request for audit page.

and use `?source=NTF*` for all notification related on notification logs page for option 'All' (to be added).

**Comment by MarkRiddoch** [comment]
There is no need for a notifications specific entry point to fetch audit log entries. See updated comment in the Jira.

**Comment by ashish-jabble** [comment]
Closed in favour of https://github.com/foglamp/FogLAMP/pull/1720

**Pull request closed without merging**
