### PR TITLE
FOGL-1973: storage layer feeature for bulk inserts in tables

### PR DESCRIPTION
**Pull request by pintomax**
FOGL-1973: initial commit of bulk insert, sqlite only

JSON payload to pass:

{"inserts" : [
	{"value": 0, "history_ts": "2019-02-25 06:16:04.768143-05:00", "key": "BUFFERED"},
	{"value": 0, "history_ts": "2019-02-25 06:16:04.768143-05:00", "key": "UNSENT"}
   ]
}

If "inserts" property is not found, a new object with "inserts" and one element is added.

This is similar to bulk updates.

### CODE REVIEW

**Comment by AmandeepArora** [comment]
Looks good. Please continue with Postgres side changes also. And changes in statistics_history.py.

**Comment by pintomax** [comment]
@praveen-garg There is an issue with Python tests, while the functionality is ok.

Could you please take a loot a that?

**Comment by praveen-garg** [comment]
@pintomax  https://github.com/foglamp/FogLAMP/pull/1436

**Comment by pintomax** [comment]
Unit tests fixed. It looks like we can merge it to FOGL-2488.

**Pull request merged**
